## Урок 6. Взаимосвязь величин. Параметрические и непараметрические показатели корреляции. Корреляционный анализ.

#### Задание 1

Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):

zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],

ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].

Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [1]:
import numpy as np

zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [2]:
cov = (np.mean(zp * ks) - np.mean(zp) * np.mean(ks)) # Смещенная ковариация
zp_std = sum((zp - np.mean(zp)) ** 2 / len(zp)) ** 0.5 # Смещенное стандартное отклонение zp
ks_std = sum((ks - np.mean(ks)) ** 2 / len(ks)) ** 0.5 # Смещенное стандартное отклонение ks
r = cov / (zp_std * ks_std)
cov, r

(9157.839999999997, 0.8874900920739159)

In [3]:
np.cov(zp, ks, ddof=0), np.corrcoef(zp, ks)

(array([[ 3494.64,  9157.84],
        [ 9157.84, 30468.89]]),
 array([[1.        , 0.88749009],
        [0.88749009, 1.        ]]))

In [4]:
cov = len(zp) / (len(zp) - 1) * (np.mean(zp * ks) - np.mean(zp) * np.mean(ks)) # Несмещенная ковариация
zp_std = sum((zp - np.mean(zp)) ** 2 / (len(zp) - 1)) ** 0.5 # Несмещенное стандартное отклонение zp
ks_std = sum((ks - np.mean(ks)) ** 2 / (len(ks) - 1)) ** 0.5 # Несмещенное стандартное отклонение ks
r = cov / (zp_std * ks_std)
cov, r

(10175.377777777774, 0.887490092073916)

In [5]:
np.cov(zp, ks, ddof=1), np.corrcoef(zp, ks)

(array([[ 3882.93333333, 10175.37777778],
        [10175.37777778, 33854.32222222]]),
 array([[1.        , 0.88749009],
        [0.88749009, 1.        ]]))

#### Задание 2

Измерены значения IQ выборки студентов, обучающихся в местных технических вузах:

131, 125, 115, 122, 131, 115, 107, 99, 125, 111.

Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [6]:
iq = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])

n = len(iq)
mean = iq.mean()
std = iq.std(ddof=1)
t = 2.262

mean - t * std / n ** 0.5, mean + t * std / n ** 0.5

(110.55660776308164, 125.64339223691834)

#### Задание 3
Известно, что рост футболистов в сборной распределен нормально с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27, среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.

In [7]:
n = 27
std = 25 ** 0.5
mean = 174.2
z = 1.96

mean - z * std / n ** 0.5, mean + z * std / n ** 0.5

(172.31398912064722, 176.08601087935276)